#!/bin/sh

mkdir -p $HOME/.ssh

echo $HOME:
ls $HOME/authorized_keys.d

for f in $HOME/authorized_keys.d/*; do
	user=$(basename $f .pub);
	user=${user%@*}
	echo -n "command=\"~fram/fram $user\" "
	head -n 1 $f
done > $HOME/.ssh/authorized_keys

chmod 600 $HOME/.ssh/authorized_keys
